# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YjZmZDNlMjhhMWNkYTIzMDcxYTI1OTVkZWRmY2JkMTY0ZmJjMDAxZTJkODZjNTlmYzhmNGMyZmMzMzA3OGYwMDY3MzUxM2VlNzA5ZDg3NjQ2ZGJkMjEwYTkwMTUwYTFkNTU5NjY5MDcxNGNjN2MzZDcxYjQ1ZGM1OGIwNDUzMjY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
